version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
        - image: circleci/android:api-27-alpha
    resource_class: medium+
    steps:
        - checkout
        - run:
             name: Download Dependencies
             command: ./gradlew androidDependencies
        - save_cache:
             paths:
                - ~/.gradle
             key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        - persist_to_workspace:
             root: .
             paths:
               - .git
               - config
        - run:
            name: Run Build
            command: ./gradlew assemble
        - store_artifacts:
            path: app/build/outputs/apk/release/
            destination: apks/

workflows:
   version: 2
   nightly:
     jobs:
       - build:
          filters:
            branches:
              only: 
                - dev
                - master

